FROM node:18.17.1-bullseye-slim

WORKDIR /workspaces/app

COPY package.json .
COPY package-lock.json .

RUN npm ci

COPY tsconfig.json .
COPY tsconfig.build.json .

COPY src src

RUN npm run build

CMD ["node", "dist/main"]

