FROM oven/bun:1

WORKDIR /workspaces/app

COPY package.json .
COPY bun.lockb .

RUN bun install

COPY tsconfig.json .
COPY tsconfig.build.json .

COPY src src

RUN bun run build

CMD ["bun", "/workspaces/app/dist/main"]
